version: '3'
services:

  mysql:
    build:
      context: ./docker/mysql
    container_name: docker-mysql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_USER: dino
      MYSQL_PASSWORD: dino
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: alumnosdb
    restart: always

  web:
    build:
      context: ./docker/php
    container_name: docker-php
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
